export interface PlatformConfigField {
  key: string;
  label: string;
  type: 'text' | 'password' | 'url' | 'number' | 'toggle';
  placeholder?: string;
  helpText?: string;
  required: boolean;
  secretType?: string;
}

export interface PlatformRegistryEntry {
  key: string;
  displayName: string;
  description: string;
  category: 'issue-tracker' | 'error-monitoring' | 'version-control' | 'project-management';
  iconSlug: string;
  defaultDirection: 'inbound' | 'outbound' | 'both';
  defaultIntakeMode: 'webhook' | 'polling' | 'manual';
  supportsCustomServer: boolean;
  supportsOAuth: boolean;
  configFields: PlatformConfigField[];
}

export const PLATFORM_REGISTRY: Record<string, PlatformRegistryEntry> = {
  sentry: {
    key: 'sentry',
    displayName: 'Sentry',
    description: 'Monitor production errors and ingest Sentry issues through a shared connector contract.',
    category: 'error-monitoring',
    iconSlug: 'sentry',
    defaultDirection: 'inbound',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: true,
    supportsOAuth: false,
    configFields: [
      {
        key: 'auth_token',
        label: 'Auth Token',
        type: 'password',
        placeholder: 'Paste a Sentry auth token',
        helpText: 'Use a Sentry token with permission to read organization, project, and issue data.',
        required: true,
        secretType: 'api_key',
      },
      {
        key: 'api_base_url',
        label: 'API Base URL',
        type: 'url',
        placeholder: 'https://sentry.io',
        helpText: 'Leave the hosted Sentry URL or replace it with your self-hosted Sentry base URL.',
        required: false,
      },
      {
        key: 'org_slug',
        label: 'Organization Slug',
        type: 'text',
        placeholder: 'acme-platform',
        helpText: 'Enter the Sentry organization slug that owns the projects you want to ingest.',
        required: true,
      },
      {
        key: 'webhook_secret',
        label: 'Webhook Secret',
        type: 'password',
        placeholder: 'Paste the Sentry webhook signing secret',
        helpText: 'Store the shared secret used to verify webhook signatures from Sentry.',
        required: false,
        secretType: 'webhook_secret',
      },
      {
        key: 'integration_id',
        label: 'Integration ID',
        type: 'text',
        placeholder: '123456',
        helpText: 'Optional Sentry integration identifier used when your setup needs a specific installed integration.',
        required: false,
      },
    ],
  },
  crashlytics: {
    key: 'crashlytics',
    displayName: 'Firebase Crashlytics',
    description: 'Receive mobile crash reports from Firebase Crashlytics using shared connector configuration.',
    category: 'error-monitoring',
    iconSlug: 'firebase-crashlytics',
    defaultDirection: 'inbound',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: false,
    supportsOAuth: false,
    configFields: [
      {
        key: 'service_account_json',
        label: 'Service Account JSON',
        type: 'password',
        placeholder: 'Paste the Firebase service account JSON',
        helpText: 'Provide the full service account JSON for a Google Cloud account that can read Crashlytics data.',
        required: true,
        secretType: 'service_account',
      },
      {
        key: 'project_id',
        label: 'Project ID',
        type: 'text',
        placeholder: 'support-agent-prod',
        helpText: 'Enter the Firebase project ID that contains the Crashlytics app you want to connect.',
        required: true,
      },
    ],
  },
  linear: {
    key: 'linear',
    displayName: 'Linear',
    description: 'Sync issues and comments with Linear for inbound intake and outbound follow-up.',
    category: 'issue-tracker',
    iconSlug: 'linear',
    defaultDirection: 'both',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: false,
    supportsOAuth: true,
    configFields: [
      {
        key: 'api_key',
        label: 'API Key',
        type: 'password',
        placeholder: 'Paste a Linear API key',
        helpText: 'Use a Linear API key with access to the workspace, teams, and projects you want to automate.',
        required: true,
        secretType: 'api_key',
      },
      {
        key: 'team_id',
        label: 'Team ID',
        type: 'text',
        placeholder: 'ENG',
        helpText: 'Set the default Linear team identifier for newly ingested or updated issues.',
        required: true,
      },
      {
        key: 'project_id',
        label: 'Project ID',
        type: 'text',
        placeholder: 'c8f3c4fd-9d31-4f0e-a8d7-2d4b6a84d111',
        helpText: 'Optionally scope issue creation and routing to a specific Linear project.',
        required: false,
      },
      {
        key: 'webhook_secret',
        label: 'Webhook Secret',
        type: 'password',
        placeholder: 'Paste the Linear webhook secret',
        helpText: 'Store the webhook secret so inbound Linear events can be verified before intake.',
        required: false,
        secretType: 'webhook_secret',
      },
    ],
  },
  github: {
    key: 'github',
    displayName: 'GitHub',
    description: 'Connect repositories and pull request events from GitHub or GitHub Enterprise.',
    category: 'version-control',
    iconSlug: 'github',
    defaultDirection: 'both',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: true,
    supportsOAuth: true,
    configFields: [
      {
        key: 'access_token',
        label: 'Access Token',
        type: 'password',
        placeholder: 'Paste a GitHub personal access token',
        helpText: 'Use a token that can read repositories, issues, and webhook-related metadata for the target org.',
        required: true,
        secretType: 'api_key',
      },
      {
        key: 'api_base_url',
        label: 'API Base URL',
        type: 'url',
        placeholder: 'https://api.github.com',
        helpText: 'Keep the public GitHub API URL or replace it with your GitHub Enterprise API endpoint.',
        required: false,
      },
      {
        key: 'webhook_secret',
        label: 'Webhook Secret',
        type: 'password',
        placeholder: 'Paste the GitHub webhook secret',
        helpText: 'Use the same secret configured on the GitHub webhook so inbound events can be authenticated.',
        required: false,
        secretType: 'webhook_secret',
      },
    ],
  },
  github_issues: {
    key: 'github_issues',
    displayName: 'GitHub Issues',
    description: 'Use GitHub Issues as an issue tracker for intake, comment sync, and outbound updates.',
    category: 'issue-tracker',
    iconSlug: 'github-issues',
    defaultDirection: 'both',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: true,
    supportsOAuth: true,
    configFields: [
      {
        key: 'access_token',
        label: 'Access Token',
        type: 'password',
        placeholder: 'Paste a GitHub personal access token',
        helpText: 'Use a token that can read and write issues, comments, labels, and repository metadata.',
        required: true,
        secretType: 'api_key',
      },
      {
        key: 'api_base_url',
        label: 'API Base URL',
        type: 'url',
        placeholder: 'https://api.github.com',
        helpText: 'Leave the hosted API URL or point this at a GitHub Enterprise API base URL.',
        required: false,
      },
      {
        key: 'webhook_secret',
        label: 'Webhook Secret',
        type: 'password',
        placeholder: 'Paste the GitHub webhook secret',
        helpText: 'Store the shared secret used to verify GitHub issue and comment webhook deliveries.',
        required: false,
        secretType: 'webhook_secret',
      },
      {
        key: 'repo_owner',
        label: 'Repository Owner',
        type: 'text',
        placeholder: 'acme-inc',
        helpText: 'Optionally scope this connector to a default GitHub organization or user account.',
        required: false,
      },
      {
        key: 'repo_name',
        label: 'Repository Name',
        type: 'text',
        placeholder: 'support-agent',
        helpText: 'Optionally set a default repository for issue intake and outbound updates.',
        required: false,
      },
    ],
  },
  jira: {
    key: 'jira',
    displayName: 'Jira',
    description: 'Integrate Atlassian Jira projects for issue intake, updates, and workflow routing.',
    category: 'issue-tracker',
    iconSlug: 'jira',
    defaultDirection: 'both',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: true,
    supportsOAuth: false,
    configFields: [
      {
        key: 'api_token',
        label: 'API Token',
        type: 'password',
        placeholder: 'Paste an Atlassian API token',
        helpText: 'Use an Atlassian API token for the account that will read and update Jira issues.',
        required: true,
        secretType: 'api_key',
      },
      {
        key: 'user_email',
        label: 'User Email',
        type: 'text',
        placeholder: 'automation@acme.com',
        helpText: 'Enter the Atlassian account email paired with the API token.',
        required: true,
      },
      {
        key: 'api_base_url',
        label: 'API Base URL',
        type: 'url',
        placeholder: 'https://your-org.atlassian.net',
        helpText: 'Provide the Jira Cloud site URL or your self-hosted Jira base URL.',
        required: true,
      },
      {
        key: 'project_key',
        label: 'Project Key',
        type: 'text',
        placeholder: 'SUP',
        helpText: 'Optionally default new or synced work to a specific Jira project key.',
        required: false,
      },
      {
        key: 'webhook_secret',
        label: 'Webhook Secret',
        type: 'password',
        placeholder: 'Paste the Jira webhook secret',
        helpText: 'Store the shared secret or signing value used to validate Jira webhook deliveries.',
        required: false,
        secretType: 'webhook_secret',
      },
    ],
  },
  trello: {
    key: 'trello',
    displayName: 'Trello',
    description: 'Connect Trello boards for card-based intake, routing, and outbound status updates.',
    category: 'project-management',
    iconSlug: 'trello',
    defaultDirection: 'both',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: false,
    supportsOAuth: false,
    configFields: [
      {
        key: 'api_key',
        label: 'API Key',
        type: 'password',
        placeholder: 'Paste a Trello API key',
        helpText: 'Use the Trello API key from the workspace that owns the boards you want to connect.',
        required: true,
        secretType: 'api_key',
      },
      {
        key: 'api_token',
        label: 'API Token',
        type: 'password',
        placeholder: 'Paste a Trello API token',
        helpText: 'Provide the Trello member token that authorizes card reads, writes, and webhook setup.',
        required: true,
        secretType: 'api_token',
      },
      {
        key: 'board_id',
        label: 'Board ID',
        type: 'text',
        placeholder: '65f3d2a91c7b2e14e8f41a2b',
        helpText: 'Optionally restrict this connector to a default Trello board for card intake and updates.',
        required: false,
      },
      {
        key: 'webhook_secret',
        label: 'Webhook Secret',
        type: 'password',
        placeholder: 'Paste the Trello webhook secret',
        helpText: 'Store the webhook verification secret if your Trello integration is configured with one.',
        required: false,
        secretType: 'webhook_secret',
      },
    ],
  },
  gitlab: {
    key: 'gitlab',
    displayName: 'GitLab',
    description: 'Connect GitLab repositories and merge request events from cloud or self-managed instances.',
    category: 'version-control',
    iconSlug: 'gitlab',
    defaultDirection: 'both',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: true,
    supportsOAuth: true,
    configFields: [
      {
        key: 'access_token',
        label: 'Access Token',
        type: 'password',
        placeholder: 'Paste a GitLab access token',
        helpText: 'Use a GitLab token with permission to read projects, merge requests, and webhook metadata.',
        required: true,
        secretType: 'api_key',
      },
      {
        key: 'api_base_url',
        label: 'API Base URL',
        type: 'url',
        placeholder: 'https://gitlab.com',
        helpText: 'Keep the GitLab.com URL or replace it with the base URL of your self-managed GitLab instance.',
        required: false,
      },
      {
        key: 'webhook_secret',
        label: 'Webhook Secret',
        type: 'password',
        placeholder: 'Paste the GitLab webhook secret token',
        helpText: 'Use the same secret token configured on GitLab webhooks so events can be verified.',
        required: false,
        secretType: 'webhook_secret',
      },
    ],
  },
  bitbucket: {
    key: 'bitbucket',
    displayName: 'Bitbucket',
    description: 'Integrate Bitbucket repositories and pull request activity from cloud or self-hosted setups.',
    category: 'version-control',
    iconSlug: 'bitbucket',
    defaultDirection: 'both',
    defaultIntakeMode: 'webhook',
    supportsCustomServer: true,
    supportsOAuth: false,
    configFields: [
      {
        key: 'app_password',
        label: 'App Password',
        type: 'password',
        placeholder: 'Paste a Bitbucket app password',
        helpText: 'Use a Bitbucket app password with repository and issue access for the target workspace.',
        required: true,
        secretType: 'api_key',
      },
      {
        key: 'username',
        label: 'Username',
        type: 'text',
        placeholder: 'support-agent-bot',
        helpText: 'Enter the Bitbucket username that owns the app password credentials.',
        required: true,
      },
      {
        key: 'api_base_url',
        label: 'API Base URL',
        type: 'url',
        placeholder: 'https://api.bitbucket.org/2.0',
        helpText: 'Leave the Bitbucket Cloud API URL or set the API base for your Bitbucket Server deployment.',
        required: false,
      },
      {
        key: 'workspace',
        label: 'Workspace',
        type: 'text',
        placeholder: 'acme-engineering',
        helpText: 'Optionally scope the connector to a default Bitbucket workspace for repository lookups.',
        required: false,
      },
      {
        key: 'webhook_secret',
        label: 'Webhook Secret',
        type: 'password',
        placeholder: 'Paste the Bitbucket webhook secret',
        helpText: 'Store the secret used to validate Bitbucket webhook requests before processing.',
        required: false,
        secretType: 'webhook_secret',
      },
    ],
  },
};

export const PLATFORM_CATEGORIES = [
  { key: 'error-monitoring', label: 'Error Monitoring' },
  { key: 'issue-tracker', label: 'Issue Trackers' },
  { key: 'version-control', label: 'Version Control' },
  { key: 'project-management', label: 'Project Management' },
] as const;
